# Generated by Django 3.2.13 on 2022-11-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=50)),
                ('character_MBTI_type', models.CharField(max_length=4)),
                ('movie_title', models.TextField()),
                ('character_img_path', models.TextField()),
            ],
        ),
    ]
