# Generated by Django 3.2.13 on 2022-11-22 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0003_movie_comment_movie_comment_like_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_like_users',
            field=models.ManyToManyField(related_name='like_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
